const tr = [
  {
    auth: {
      signIn: {
        email: "E-posta",
        password: "Şifre",
        login: "Giriş Yap",
        register: "Üyelik Oluştur",
        title: "Kullanıcı Girişi",
        language: "Dil",
        forgot: "Şifreni mi unuttun?",
        forgotButton: "Şifremi Unuttum",
        successRecorded: "Giriş Yapıldı",
        policyInfo: "K.V.K.K kapsamında kişisel bilgileriniz saklanmaktadır.",
        policy: "Gizlilik Politikası",
        and: " ve ",
        terms: "Kullanım Koşullarını",
        inspect: " inceleyin.",
      },
      signUp: {
        fullName: "Ad Soyad",
        phoneNumber: "Telefon Numarası",
        email: "E-posta",
        password: "Şifre",
        rePassword: "Şifre Tekrar",
        login: "Giriş Yap",
        register: "Üyelik Oluştur",
        title: "Yeni Üyelik",
        language: "Dil",
        allReady: "Zaten bir hesabın var mı?",
        allReadyButton: "Giriş Yap",
        successRecorded: "Kayıt Yapıldı",
        policyInfo: "Üye olarak Gizlilik Politikamızı kabul etmiş olursunuz.",
        policy: "Gizlilik Politikası",
        and: " ve ",
        terms: "Kullanım Koşullarını",
        inspect: " inceleyin.",
        mailStatus: false,
        confirmationCode: "Doğrulama Kodu",
        confirmationCodeInfo:
          "Lütfen cep telefonunuza gönderilen doğrulama kodunu girin.",
        resendCode: "Kodu Tekrar Gönder",
        confirmationCodeError:
          "Aktivasyon kodunun süresi dolmuştur, lütfen tekrar gönderin.",
        checkOne: "En az 6 karakter",
        checkTwo: "En az 1 büyük ve 1 küçük harf",
        checkThree: "En az 1 rakam",
        checkFour: "En az 1 özel karakter",
        checkPassword: "Şifre Doğrulama",
      },
    },
  },
];
export default tr;
