export const colors = {
  aliceBlue: "#f0f8ff",
  antiqueWhite: "#faebd7",
  aqua: "#00ffff",
  aquaMarine: "#7fffd4",
  black: "#000",
  indianRed: "#cd5c5c",
  lightGrey: "#DEDEDE",
  lightRed: "#ffe6e6",
  lightSeaGreen: "#20b2aa",
  lightSkyBlue: "#87cefa",
  grey: "#7D7D7D",
  red: "#ff0000",
  white: "#ffffff",
  opacityBlack: "rgba(0,0,0,0.5)",
};
