export const colors = {
  aliceblue: "#f0f8ff",
  antiquewhite: "#faebd7",
  aqua: "#00ffff",
  aquamarine: "#7fffd4",
  black: "#000",
  indianred: "#cd5c5c",
  lightseagreen: "#20b2aa",
  lightskyblue: "#87cefa",
  grey: "#7D7D7D",
  lightGrey: "#DEDEDE",
  red: "#ff0000",
  white: "#ffffff",
  opacityBlack: "rgba(0,0,0,0.5)",
};
